### PR TITLE
fix: metrics stream can't be deleted

### LINKED ISSUE #9709: stream can't be deleted :node_memory_MemAvailable_bytes:sum
### Bug Description

We have some metrics stream name like this `:node_memory_MemAvailable_bytes:sum`, but this can't be deleted.

### Priority

P0 - Critical

### Severity

Blocker

### Related Story/Issue

_No response_

### Is this a regression?

Yes

### Steps to Reproduce (Optional)

_No response_

### Environment Details

```yaml
version: 0.30.0
```

### Which OpenObserve Functionalities Are Affected?

- [ ] Login
- [ ] Landing Page
- [ ] Logs
- [ ] Dashboards
- [x] Streams
- [ ] Functions
- [ ] Ingestion
- [ ] Alerts
- [ ] Pipelines
- [ ] Metrics
- [ ] Traces
- [ ] Real User Monitoring (RUM)
- [ ] Reports
- [ ] Data Sources
- [ ] IAM
- [ ] Management
- [ ] Cosmetic
- [ ] Not Known / Other

### PR DESCRIPTION
**Pull request by hengfeiyang**
### **User description**
fixed #9709

___

### **PR Type**
Bug fix

___

### **Description**
- Remove stream name formatting on delete

- Normalize metric names in Prometheus remote_write

- Bump version to 0.40.0

___

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mod.rs</strong><dd><code>Remove stream name formatting on delete</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/handler/http/request/stream/mod.rs

<ul><li>Removed conditional formatting of stream_name in delete<br> <li> Now uses raw stream_name for deletion</ul>

</details>

  </td>
  <td><a href="https://github.com/openobserve/openobserve/pull/9710/files#diff-619eafba0f0509d905b021f4a16659010aca23c62cffd9cd3e6c2bbe204ce200">+1/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>prom.rs</strong><dd><code>Format metric names in remote_write</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/service/metrics/prom.rs

<ul><li>Apply format_stream_name to metric_name<br> <li> Ensure consistent naming for metrics streams</ul>

</details>

  </td>
  <td><a href="https://github.com/openobserve/openobserve/pull/9710/files#diff-c4e9e1d49a2bd0fefe67684b3768c4792be63cebcf727d71a48141f5b5957b8c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Cargo.toml</strong><dd><code>Bump package version to 0.40.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Cargo.toml

- Bump package version from 0.17.0 to 0.40.0

</details>

  </td>
  <td><a href="https://github.com/openobserve/openobserve/pull/9710/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

**Review by uddhavdave — APPROVED** [review]

File: src/service/metrics/prom.rs [hunk 1]
```diff
@@ -196,7 +196,7 @@ pub async fn remote_write(
             .collect();
 
         let metric_name = match labels.get(NAME_LABEL) {
-            Some(v) => v.to_owned(),
+            Some(v) => format_stream_name(v.to_string()),
```
Comment (YashodhanJoshi1) [inline src/service/metrics/prom.rs:199]: here should we have a check for skip formatting stream names?

**Review by oasisk — APPROVED** [review]

File: src/service/metrics/prom.rs (hunk 1 above)
Comment (hengfeiyang) [reply src/service/metrics/prom.rs:199]: for metrics we don't need it, that option only for logs for the big customer.
