### PR TITLE
fix: enable rbac for index streams

### LINKED ISSUE #3904: RBAC: rbac users not able to access index stream
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

- RBAC users not able to get the list of index streams even if logs permission is given.
- SSO users get 403 forbidden error when querying index streams.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8-rc4
Commit Hash: a8895693669b1797bd58cb5ac0cd4b239973a002
Build Date: 2024-07-03T13:56:45Z
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Subhra264**
Fixes #3904 

## Summary by CodeRabbit

- **New Features**
  - Added support for "index" resource in role management, allowing users to manage index-related streams.

- **Refactor**
  - Simplified the handling of `stream_type` across various functions, improving code readability and maintainability.

### CODE REVIEW

**Review by haohuaijin — APPROVED** [review]

File: src/handler/http/request/search/mod.rs [hunk 1]
```diff
@@ -214,6 +214,11 @@ pub async fn search(
             let user: meta::user::User =
                 USERS.get(&format!("{org_id}/{}", user_id)).unwrap().clone();
 
+            let stream_type = if stream_type.eq(&StreamType::Index) {
+                StreamType::Logs
+            } else {
+                stream_type
+            };
```
Comment (hengfeiyang) [inline src/handler/http/request/search/mod.rs:221]: @Subhra264 now we support created index stream for `logs`, `metrics` and `traces`, so maybe this is not working.

**Review by hengfeiyang — CHANGES_REQUESTED** [review]

File: src/handler/http/request/search/mod.rs (hunk 1 above)
Comment (Subhra264) [reply src/handler/http/request/search/mod.rs:221]: Yes, will change it.

**Review by hengfeiyang — APPROVED** [review]
