### PR TITLE
fix: histogram stream sync

### LINKED ISSUE #6315: Histogram metrics stream doesn't sync in super cluster
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

We found some metrics streams didn't sync across the super cluster which is histogram metrics.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true

```

### Please provide the version you discovered this bug in (check about page for version information)

```true

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hengfeiyang**
fixed #6315

### CODE REVIEW

File: src/common/infra/ofga/mod.rs [hunk 1]
```diff
@@ -265,7 +276,7 @@ pub async fn init() -> Result<(), anyhow::Error> {
             if tuples.is_empty() {
                 log::info!("No orgs to update to the openfga");
             } else {
-                log::debug!("tuples not empty: {:#?}", tuples);
+                // log::debug!("tuples not empty: {:#?}", tuples);
```
Comment (Subhra264) [inline src/common/infra/ofga/mod.rs:279]: Can this change be reverted. This will help to check the tuples that are written during the alert folder RBAC migrations and possible issues

**Review by Subhra264 — APPROVED** [review]

**Review by Subhra264 — APPROVED** [review]
