### PR TITLE
fix: return 404 if the delete target not exists

### LINKED ISSUE #1703: API returns 200 after trying to delete a template that does not exists
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

API endpoint 
```
api/{org_id}/alerts/templates/{template_name}
```

Trying to delete a template on pytest that does not exist, the API returns 200 instead of 404

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the version you discovered this bug in (check about page for version information)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by baerwang**
fixed #1703

### CODE REVIEW

File: src/service/dashboards/mod.rs [hunk 1]
```diff
@@ -97,15 +97,18 @@ pub async fn delete_dashboard(
...
+            .is_err()
+        {
+            return Ok(Response::NotFound("Dashboard deleted".to_string()).into());
+        } else {
+            Response::OkMessage("Dashboard deleted".to_owned())
+        };
+        return Ok(resp.into());
+    }
+    return Ok(Response::NotFound("Dashboard deleted".to_string()).into());
 }
```
Comment (hengfeiyang) [inline src/service/dashboards/mod.rs:112]: This code can be improved by `cargo clippy`, you can try.

**Comment by hengfeiyang** [comment]
@baerwang The issue description is `template` you are working on `dashboard`, maybe you need working on both of `dashboard` and `template`

**Review by hengfeiyang — APPROVED** [review]
