### PR TITLE
fix: allow IPv6 addresses in RUM headers

### LINKED ISSUE #4080: Parsing IPv6 addresses is failing
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

While testing this PR: https://github.com/openobserve/openobserve/pull/4068 I discovered that parsing of IPv6 is not working.

From the log:
2024-07-27T14:22:59.448784305+00:00 ERROR openobserve::common::meta::middleware_data: Error parsing IP address: 2a00:fd00:811f:b500:e0b5:be6d:7426:5d36, invalid IP address syntax

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
From the log:
2024-07-27T14:22:59.448784305+00:00 ERROR openobserve::common::meta::middleware_data: Error parsing IP address: 2a00:fd00:811f:b500:e0b5:be6d:7426:5d36, invalid IP address syntax
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
openobserve-dev:v0.10.9-rc2-2b3e672
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by uddhavdave**
fixes #4080

## Summary by CodeRabbit

- **New Features**
	- Improved IP address parsing logic to handle both `IpAddr` and `SocketAddr`, enhancing versatility with input formats.
	- Added a fallback mechanism to default to the loopback address in case of parsing failure.

- **Bug Fixes**
	- Enhanced error handling in IP address parsing to ensure functionality with invalid input.

- **Tests**
	- Introduced a new asynchronous test function to validate the updated IP parsing logic against various formats.

### CODE REVIEW

File: src/common/meta/middleware_data.rs [hunk 1]
```diff
@@ -109,13 +113,18 @@ impl RumExtraData {
...
+                .or_else(|_| {
+                    ip_address
+                        .parse::<SocketAddr>()
+                        .map(|sock_addr| sock_addr.ip())
+                        .map_err(|e| {
+                            log::error!("Error parsing IP address: {}, {}", &ip_address, e);
+                            e
+                        })
+                })
+                .unwrap_or_else(|_| IpAddr::V4(std::net::Ipv4Addr::new(127, 0, 0, 1)));
```
Comment (hengfeiyang) [inline src/common/meta/middleware_data.rs:127]: Maybe we can split this part into a function, then the unit test will be easier.

Comment (uddhavdave) [reply src/common/meta/middleware_data.rs:127]: Sure, can put this as a utils function.

**Review by hengfeiyang — APPROVED** [review]
