### PR TITLE
fix: RUM error explorer UI issues

### LINKED ISSUE #2982: Rum: Known issues
real user monitoring

### Is this a regression?

Yes

### Description

- [x] Error displayed on Error sessions Tracking page when there are no Errors on the page to display.
- [x] Sometimes the panels overlap each other 
- [x] Unknown user displayed under tags 
- [ ] Improvement - Keep 1 selected data same after switching between tabs on RUM 
- [ ] Add pagination for sessions and error tracking

Screenshot 2024-03-14 at 9 21 10 PM
Screenshot 2024-03-14 at 9 26 33 PM
### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the version you discovered this bug in (check about page for version information)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by omkarK06**
fix #2982
1. Fix RUM performance dashboards overlapping issue
2. Fixed search field not found issues in Error Explorer when data is not present
3. Fixed filtering of session events in session viewer
4. Partition key not getting restored in UI after saving  #2976

### CODE REVIEW

**Review by oasisk — APPROVED** [review]

**Review by hengfeiyang — APPROVED** [review]

**Review by neha00290 — APPROVED** [review]

File: web/src/components/rum/PlayerEventsSidebar.vue [hunk 1]
```diff
@@ -150,18 +155,18 @@ const eventOptions = [
...
-          event?.type.toLowerCase().includes(value.toString().toLowerCase())
-        );
-      })
-    );
-  } else {
-    filteredEvents.value = cloneDeep(props.events);
+  if (value === null) {
+    value = "";
   }
+  const _value = value.toString();
```
Comment (bjp232004) [inline web/src/components/rum/PlayerEventsSidebar.vue:161]: can't we avoid clonedeep?

Comment (omkarK06) [reply web/src/components/rum/PlayerEventsSidebar.vue:160]: Yes, removed it
