### PR TITLE
fix: cache with query size

### LINKED ISSUE #10382: Selecting the number of rows does not take effect when downloading results for custom range
### Bug Description

The number of rows selected when modifying 'Record Count' does not take effect.
It will continue to use the previously selected (or default) number of rows. 
Only modifying 'Initial Number' will take effect when I downloading results for custom range.

### Priority

P1 - High

### Severity

Blocker

### Related Story/Issue

_No response_

### Is this a regression?

Yes

### Steps to Reproduce (Optional)

_No response_

### Environment Details

```yaml
Version: v0.50.3
docker images: public.ecr.aws/zinclabs/openobserve:latest 
Docker run with thress clusters
```

### Which OpenObserve Functionalities Are Affected?

- [ ] Login
- [ ] Landing Page
- [x] Logs
- [ ] Dashboards
- [ ] Streams
- [x] Functions
- [ ] Ingestion
- [ ] Alerts
- [ ] Pipelines
- [ ] Metrics
- [ ] Traces
- [ ] Real User Monitoring (RUM)
- [ ] Reports
- [x] Data Sources
- [ ] IAM
- [ ] Management
- [ ] Cosmetic
- [ ] Not Known / Other

### PR DESCRIPTION
**Pull request by hengfeiyang**
### **User description**

- [x] fixed #10382
- [x] fixed `histogram(_timestamp, 60000)`, this is invalid interval

___

### **PR Type**
Bug fix

___

### **Description**
- Include `query.size` in cache hash

- Prevent cache collisions across sizes

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["prepare_cache_response"] 
  B["Build cache hash_body"]
  C["Cache key includes size"]
  A -- "computes" --> B
  B -- "now adds req.query.size" --> C
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mod.rs</strong><dd><code>Add query size to cache hashing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/service/search/cache/mod.rs

<ul><li>Add <code>req.query.size</code> to <code>hash_body</code> inputs<br> <li> Ensure cache key varies by requested size</ul>

</details>

  </td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10384/files#diff-f07bfacc0501b9c234e64b16c1dd8eb0ae8fcbe231f90c81fed72bcc94946f74">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: src/service/search/cache/mod.rs [hunk 1]
```diff
@@ -558,7 +558,11 @@ pub async fn prepare_cache_response(
     }
 
     // calculate hash for the query with version (after normalizing histogram interval)
-    let mut hash_body = vec![CACHE_VERSION.to_string(), origin_sql.to_string()];
+    let mut hash_body = vec![
+        CACHE_VERSION.to_string(),
+        origin_sql.to_string(),
+        req.query.size.to_string(),
```
Comment (haohuaijin) [inline src/service/search/cache/mod.rs:564]: should also hash from?

Comment (Loaki07) [reply src/service/search/cache/mod.rs:564]: we don't support pagination cache, only cache when from=0

Comment (haohuaijin) [reply src/service/search/cache/mod.rs:564]: got it
