### PR TITLE
fix: logs large records optimisation

### LINKED ISSUE #10185: 🐛 Frontend freezes when query returns very large log fields
### Bug Description

When querying logs that contain very large fields (e.g. large JSON payloads or long text fields), the frontend becomes extremely slow or completely unresponsive.
In some cases, the browser tab freezes and shows “Page Unresponsive”.

This makes it very difficult to query or analyze logs with large message/body fields.

### Priority

P1 - High

### Severity

Blocker

### Related Story/Issue

_No response_

### Is this a regression?

Yes

### Steps to Reproduce (Optional)

_No response_

### Environment Details

```yaml
Release v0.50.1
```

### Which OpenObserve Functionalities Are Affected?

- [ ] Login
- [ ] Landing Page
- [x] Logs
- [ ] Dashboards
- [ ] Streams
- [ ] Functions
- [ ] Ingestion
- [ ] Alerts
- [ ] Pipelines
- [ ] Metrics
- [ ] Traces
- [ ] Real User Monitoring (RUM)
- [ ] Reports
- [ ] Data Sources
- [ ] IAM
- [ ] Management
- [ ] Cosmetic
- [ ] Not Known / Other

### PR DESCRIPTION
**Pull request by oasisk**
fixed #10185

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fix oversized hit handling in chunk iterator

- Implement worker-level deduplication & abort

- Stream handler cleanup and dedupe updates

- Enhance log rendering with truncation & progressive

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["ResponseChunkIterator (search.rs)"] -- "pop_front oversized hits" --> B["StreamWorker"]
  B -- "deduplicate messages & abort" --> C["useHttpStreaming"]
  C -- "handle streaming hits" --> D["useSearchResponseHandler"]
  D -- "optimize rendering" --> E["useLogsHighlighter"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td><strong>useSearchResponseHandler.ts</strong><dd><code>Refactor streaming hits assignment using local variable</code>&nbsp; &nbsp; </dd></td>
  <td><a href=""></a></td>

</tr>

<tr>
  <td><strong>useLogsHighlighter.ts</strong><dd><code>Add size estimation, truncation, and progressive rendering</code></dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-ad7744a2edc4764be1c7d67feb7fe1473536af245821898a9136256b3aeb0342">+237/-38</a></td>

</tr>

<tr>
  <td><strong>DetailTable.vue</strong><dd><code>Enable disable-truncation prop in detail view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-80552b5d25fa6cef9fbbe430b1865d761c4b132284c2d2175afceea8cbabc8c7">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>IndexList.vue</strong><dd><code>Use $el to query and reset scroll container</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-08f058f883b659e713e606991a7ea37ae1ff016b7cccef970489ab5840dc3d09">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>streamWorker.js</strong><dd><code>Implement message deduplication and abort logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-8534facfcca68c16701832f43a501abcdb92847115c46fced5d69792e5594dd9">+63/-1</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Error handling</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>useStreamingSearch.ts</strong><dd><code>Handle abort_stream message and cleanup listeners</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-8fce3e25a161cd458e734bd9b1f98aadefe3482da7b6529a5b1f4fa20ec115e2">+10/-1</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>logsRenderingConfig.ts</strong><dd><code>Introduce logs rendering configuration thresholds</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-6954119ee8e2fb2791a6172bcd6a36925853fabc776e662f53bfcec8bf12fdc0">+11/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>search.rs</strong><dd><code>Pop front oversized hits to prevent infinite loop</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-373e83a31e5bbc82fba05d7ae274b0dbd624ed748272232cf7eb8b8c3b2f3afc">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Additional files</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>useSearchResponseHandler.ts</strong></td>
  <td><a href="https://github.com/openobserve/openobserve/pull/10257/files#diff-7dd7d0e65e8fe028b4969c970cf027ff39621921a41153f0a696e20478f0f858">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: src/config/src/meta/search.rs [hunk 1]
```diff
@@ -344,10 +344,11 @@ impl Iterator for ResponseChunkIterator {
             let hit = &self.remaining_hits[0];
             let hit_size = crate::utils::json::estimate_json_bytes(hit);
 
+            // If a single hit exceeds chunk size, send it alone and remove from queue
+            // CRITICAL: Must pop_front() to avoid infinite loop of duplicates
             if hit_size > self.chunk_size {
-                return Some(ResponseChunk::Hits {
-                    hits: vec![hit.to_owned()],
-                });
+                let hit = self.remaining_hits.pop_front().unwrap();
```
Comment (uddhavdave) [inline src/config/src/meta/search.rs:356]: this assumes that the `current_chunk` is empty. Let's say you have 10 logs in the `current_chunk` and the 11th log is > 20MB, we will just return the 20MB record as a chunk. So we will lose the previous records and break the order. 

So before `pop_front` we need to check if the current_chunk is not empty, if so send the chunk in the iteration and return. Next, iteration we will land on the hit where its size is >20MB and then we can safely send it as a single hit.

**Review by bjp232004 — APPROVED** [review]

File: src/config/src/meta/search.rs (hunk 1 above)
Comment (oasisk) [reply src/config/src/meta/search.rs:356]: Added a fix and Unit test for same
