### PR TITLE
fix: search partition follow query order by

### LINKED ISSUE #4603: Timeseries is not properly rendering without `order by` clause
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description
- partition api returns random order.
image

- it works properly with `order by _timeseries`, but without `order by` clause it creates issues.

https://github.com/user-attachments/assets/ebcbc0b3-e46c-40ef-8887-03f654323f9a

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the version you discovered this bug in (check about page for version information)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hengfeiyang**
fix #4603

## Summary by CodeRabbit

- **New Features**
	- Introduced a new ordering feature for search results, allowing users to specify ascending or descending order.
	- Updated search functionality to include an `order_by` parameter, enhancing the sorting of search results.

- **Bug Fixes**
	- Improved logic for determining the order of search results, ensuring clarity and accuracy in result presentation.

- **Documentation**
	- Updated comments and documentation to reflect changes in ordering logic and default behaviors.

### CODE REVIEW

File: src/service/search/mod.rs [hunk 1]
```diff
@@ -389,11 +391,15 @@ pub async fn search_partition(
...
-        if field == &ts_column.unwrap() && !sort {
+
+    // We need to reverse partitions if query is ASC order
+    if let Some((field, order_by)) = sql.order_by.first() {
+        if field == &ts_column.unwrap() && order_by == &OrderBy::Asc {
+            resp.order_by = OrderBy::Asc;
             partitions.reverse();
         }
     }
+
```
Comment (uddhavdave) [inline src/service/search/mod.rs:402]: @hengfeiyang we should add the order in response, or let the FE figure it out?

**Review by uddhavdave — APPROVED** [review]

File: src/service/search/mod.rs (hunk 1 above)
Comment (hengfeiyang) [reply src/service/search/mod.rs:402]: added, previous line.
